#ifndef __ENUM__
#define __ENUM__    

class Gramatica {
public:
	static const int EoF = 0,
	ID = 1,
	MAIN = 2,
	INT = 3,
	FLOAT = 4,
	CHAR = 5,
	IF = 6,
	ELSE = 7,	
	WHILE = 8,
	DO = 9,
	SOMA = 10,
	SUBTRACAO = 11,
	DIVISAO = 12,
	MULTIPLICACAO = 13,
	MAIOR = 14,
	MAIORIGUAL = 15,
	MENOR = 16,
	MENORIGUAL = 17,
	IGUAL = 18,
	ATRIBUICAO = 19,
	DIFERENCA = 20,	
	PONTOVIRGULA = 21,
	VIRGULA = 22,
	ABRECHAVE = 23,
	ABREPARENTESES = 24,
	FECHACHAVE = 25,
	FECHAPARENTESES = 26,
	TIPOINT = 27,
	TIPOFLOAT = 28,
	TIPOCHAR = 29,
	FOR = 30;
};

#endif